name: aqua-marina
channels:
  - conda-forge
dependencies:
  - python=3.11
  - imageio
  - ipykernel # required for jupyter notebook in VS Code
  - ipympl
  - matplotlib
  - pillow
  - scikit-image
  - ruff
  - black
